[package]
name = "cake-lex"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-set = "0.8.0"
serde = { version = "1.0.204", features = ["derive"] }
cake-util = { path = "../cake-util" }
thiserror = "1.0.63"