[package]
name = "cake-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = { workspace = true }
cake = { path = "../cake" }
cake-re = { path = "../cake-re" }
clap = { workspace = true, features = ["derive"] }
