[package]
name = "cake-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.4"
cake = { path = "../cake" }
cake-re = { path = "../cake-re" }
clap = { version = "4.5.16", features = ["derive"] }
