use crate::scanner::lexemes::{LexemeSet, LexemeIterator};

#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum CLexemes {
    Auto,
    Break,
    Case,
    Char,
    Const,
    Continue,
    Default,
    Do,
    Double,
    Else,
    Enum,
    Extern,
    Float,
    For,
    Goto,
    If,
    Inline,
    Int,
    Long,
    Register,
    Restrict,
    Return,
    Short,
    Signed,
    Sizeof,
    Static,
    Struct,
    Switch,
    Typedef,
    Union,
    Unsigned,
    Void,
    Volatile,
    While,
    Bool,
    Complex,
    Imaginary,
    Identifier,
    IntegerConst,
    FloatConst,
    OctalCharConst,
    CharConst,
    StringConst,
    LBracket,
    RBracket,
    LParen,
    RParen,
    LBrace,
    RBrace,
    Dot,
    Arrow,
    Increment,
    Decrement,
    BitAnd,
    Star,
    Plus,
    Minus,
    Tilde,
    Bang,
    Slash,
    Percent,
    LShift,
    RShift,
    Lt,
    Gt,
    Leq,
    Geq,
    Eq,
    Neq,
    Xor,
    BitOr,
    And,
    Or,
    Question,
    Colon,
    Semicolon,
    Ellipsis,
    Assign,
    MultAssign,
    DivAssign,
    ModAssign,
    AddAssign,
    SubAssign,
    LShiftAssign,
    RShiftAssign,
    AndAssign,
    XorAssign,
    OrAssign,
    Comma,
    Comment,
    MultilineComment,
    Whitespace,
    Hash,
    HeaderName,
}

impl LexemeSet for CLexemes {
    fn from_name(name: &str) -> Self {
        match name {
            "Auto" => CLexemes::Auto,
            "Break" => CLexemes::Break,
            "Case" => CLexemes::Case,
            "Char" => CLexemes::Char,
            "Const" => CLexemes::Const,
            "Continue" => CLexemes::Continue,
            "Default" => CLexemes::Default,
            "Do" => CLexemes::Do,
            "Double" => CLexemes::Double,
            "Else" => CLexemes::Else,
            "Enum" => CLexemes::Enum,
            "Extern" => CLexemes::Extern,
            "Float" => CLexemes::Float,
            "For" => CLexemes::For,
            "Goto" => CLexemes::Goto,
            "If" => CLexemes::If,
            "Inline" => CLexemes::Inline,
            "Int" => CLexemes::Int,
            "Long" => CLexemes::Long,
            "Register" => CLexemes::Register,
            "Restrict" => CLexemes::Restrict,
            "Return" => CLexemes::Return,
            "Short" => CLexemes::Short,
            "Signed" => CLexemes::Signed,
            "Sizeof" => CLexemes::Sizeof,
            "Static" => CLexemes::Static,
            "Struct" => CLexemes::Struct,
            "Switch" => CLexemes::Switch,
            "Typedef" => CLexemes::Typedef,
            "Union" => CLexemes::Union,
            "Unsigned" => CLexemes::Unsigned,
            "Void" => CLexemes::Void,
            "Volatile" => CLexemes::Volatile,
            "While" => CLexemes::While,
            "Bool" => CLexemes::Bool,
            "Complex" => CLexemes::Complex,
            "Imaginary" => CLexemes::Imaginary,
            "Identifier" => CLexemes::Identifier,
            "IntegerConst" => CLexemes::IntegerConst,
            "FloatConst" => CLexemes::FloatConst,
            "OctalCharConst" => CLexemes::OctalCharConst,
            "CharConst" => CLexemes::CharConst,
            "StringConst" => CLexemes::StringConst,
            "LBracket" => CLexemes::LBracket,
            "RBracket" => CLexemes::RBracket,
            "LParen" => CLexemes::LParen,
            "RParen" => CLexemes::RParen,
            "LBrace" => CLexemes::LBrace,
            "RBrace" => CLexemes::RBrace,
            "Dot" => CLexemes::Dot,
            "Arrow" => CLexemes::Arrow,
            "Increment" => CLexemes::Increment,
            "Decrement" => CLexemes::Decrement,
            "BitAnd" => CLexemes::BitAnd,
            "Star" => CLexemes::Star,
            "Plus" => CLexemes::Plus,
            "Minus" => CLexemes::Minus,
            "Tilde" => CLexemes::Tilde,
            "Bang" => CLexemes::Bang,
            "Slash" => CLexemes::Slash,
            "Percent" => CLexemes::Percent,
            "LShift" => CLexemes::LShift,
            "RShift" => CLexemes::RShift,
            "Lt" => CLexemes::Lt,
            "Gt" => CLexemes::Gt,
            "Leq" => CLexemes::Leq,
            "Geq" => CLexemes::Geq,
            "Eq" => CLexemes::Eq,
            "Neq" => CLexemes::Neq,
            "Xor" => CLexemes::Xor,
            "BitOr" => CLexemes::BitOr,
            "And" => CLexemes::And,
            "Or" => CLexemes::Or,
            "Question" => CLexemes::Question,
            "Colon" => CLexemes::Colon,
            "Semicolon" => CLexemes::Semicolon,
            "Ellipsis" => CLexemes::Ellipsis,
            "Assign" => CLexemes::Assign,
            "MultAssign" => CLexemes::MultAssign,
            "DivAssign" => CLexemes::DivAssign,
            "ModAssign" => CLexemes::ModAssign,
            "AddAssign" => CLexemes::AddAssign,
            "SubAssign" => CLexemes::SubAssign,
            "LShiftAssign" => CLexemes::LShiftAssign,
            "RShiftAssign" => CLexemes::RShiftAssign,
            "AndAssign" => CLexemes::AndAssign,
            "XorAssign" => CLexemes::XorAssign,
            "OrAssign" => CLexemes::OrAssign,
            "Comma" => CLexemes::Comma,
            "Comment" => CLexemes::Comment,
            "MultilineComment" => CLexemes::MultilineComment,
            "Whitespace" => CLexemes::Whitespace,
            "Hash" => CLexemes::Hash,
            "HeaderName" => CLexemes::HeaderName,
            _ => panic!("unrecognized variant")
        }
    }

    fn from_id(id: u32) -> Self {
        unsafe { std::mem::transmute::<u32, Self>(id) }
    }

    fn to_name(self) -> &'static str {
        match self {
            CLexemes::Auto => "Auto",
            CLexemes::Break => "Break",
            CLexemes::Case => "Case",
            CLexemes::Char => "Char",
            CLexemes::Const => "Const",
            CLexemes::Continue => "Continue",
            CLexemes::Default => "Default",
            CLexemes::Do => "Do",
            CLexemes::Double => "Double",
            CLexemes::Else => "Else",
            CLexemes::Enum => "Enum",
            CLexemes::Extern => "Extern",
            CLexemes::Float => "Float",
            CLexemes::For => "For",
            CLexemes::Goto => "Goto",
            CLexemes::If => "If",
            CLexemes::Inline => "Inline",
            CLexemes::Int => "Int",
            CLexemes::Long => "Long",
            CLexemes::Register => "Register",
            CLexemes::Restrict => "Restrict",
            CLexemes::Return => "Return",
            CLexemes::Short => "Short",
            CLexemes::Signed => "Signed",
            CLexemes::Sizeof => "Sizeof",
            CLexemes::Static => "Static",
            CLexemes::Struct => "Struct",
            CLexemes::Switch => "Switch",
            CLexemes::Typedef => "Typedef",
            CLexemes::Union => "Union",
            CLexemes::Unsigned => "Unsigned",
            CLexemes::Void => "Void",
            CLexemes::Volatile => "Volatile",
            CLexemes::While => "While",
            CLexemes::Bool => "Bool",
            CLexemes::Complex => "Complex",
            CLexemes::Imaginary => "Imaginary",
            CLexemes::Identifier => "Identifier",
            CLexemes::IntegerConst => "IntegerConst",
            CLexemes::FloatConst => "FloatConst",
            CLexemes::OctalCharConst => "OctalCharConst",
            CLexemes::CharConst => "CharConst",
            CLexemes::StringConst => "StringConst",
            CLexemes::LBracket => "LBracket",
            CLexemes::RBracket => "RBracket",
            CLexemes::LParen => "LParen",
            CLexemes::RParen => "RParen",
            CLexemes::LBrace => "LBrace",
            CLexemes::RBrace => "RBrace",
            CLexemes::Dot => "Dot",
            CLexemes::Arrow => "Arrow",
            CLexemes::Increment => "Increment",
            CLexemes::Decrement => "Decrement",
            CLexemes::BitAnd => "BitAnd",
            CLexemes::Star => "Star",
            CLexemes::Plus => "Plus",
            CLexemes::Minus => "Minus",
            CLexemes::Tilde => "Tilde",
            CLexemes::Bang => "Bang",
            CLexemes::Slash => "Slash",
            CLexemes::Percent => "Percent",
            CLexemes::LShift => "LShift",
            CLexemes::RShift => "RShift",
            CLexemes::Lt => "Lt",
            CLexemes::Gt => "Gt",
            CLexemes::Leq => "Leq",
            CLexemes::Geq => "Geq",
            CLexemes::Eq => "Eq",
            CLexemes::Neq => "Neq",
            CLexemes::Xor => "Xor",
            CLexemes::BitOr => "BitOr",
            CLexemes::And => "And",
            CLexemes::Or => "Or",
            CLexemes::Question => "Question",
            CLexemes::Colon => "Colon",
            CLexemes::Semicolon => "Semicolon",
            CLexemes::Ellipsis => "Ellipsis",
            CLexemes::Assign => "Assign",
            CLexemes::MultAssign => "MultAssign",
            CLexemes::DivAssign => "DivAssign",
            CLexemes::ModAssign => "ModAssign",
            CLexemes::AddAssign => "AddAssign",
            CLexemes::SubAssign => "SubAssign",
            CLexemes::LShiftAssign => "LShiftAssign",
            CLexemes::RShiftAssign => "RShiftAssign",
            CLexemes::AndAssign => "AndAssign",
            CLexemes::XorAssign => "XorAssign",
            CLexemes::OrAssign => "OrAssign",
            CLexemes::Comma => "Comma",
            CLexemes::Comment => "Comment",
            CLexemes::MultilineComment => "MultilineComment",
            CLexemes::Whitespace => "Whitespace",
            CLexemes::Hash => "Hash",
            CLexemes::HeaderName => "HeaderName",
        }
    }

    fn to_id(self) -> u32 {
        self as u32
    }

    fn pattern(self) -> &'static str {
        match self {
            CLexemes::Auto => "auto",
            CLexemes::Break => "break",
            CLexemes::Case => "case",
            CLexemes::Char => "char",
            CLexemes::Const => "const",
            CLexemes::Continue => "continue",
            CLexemes::Default => "default",
            CLexemes::Do => "do",
            CLexemes::Double => "double",
            CLexemes::Else => "else",
            CLexemes::Enum => "enum",
            CLexemes::Extern => "extern",
            CLexemes::Float => "float",
            CLexemes::For => "for",
            CLexemes::Goto => "goto",
            CLexemes::If => "if",
            CLexemes::Inline => "inline",
            CLexemes::Int => "int",
            CLexemes::Long => "long",
            CLexemes::Register => "register",
            CLexemes::Restrict => "restrict",
            CLexemes::Return => "return",
            CLexemes::Short => "short",
            CLexemes::Signed => "signed",
            CLexemes::Sizeof => "sizeof",
            CLexemes::Static => "static",
            CLexemes::Struct => "struct",
            CLexemes::Switch => "switch",
            CLexemes::Typedef => "typedef",
            CLexemes::Union => "union",
            CLexemes::Unsigned => "unsigned",
            CLexemes::Void => "void",
            CLexemes::Volatile => "volatile",
            CLexemes::While => "while",
            CLexemes::Bool => "_Bool",
            CLexemes::Complex => "_Complex",
            CLexemes::Imaginary => "_Imaginary",
            CLexemes::Identifier => "[_a-zA-Z][_a-zA-Z0-9]*",
            CLexemes::IntegerConst => "[1-9][0-9]*|(0x|0X)[0-9a-fA-F]+",
            CLexemes::FloatConst => "[\\-+]?([0-9]*\\.)?[0-9]+([eE][\\-+]?[0-9]+)?",
            CLexemes::OctalCharConst => "\\\\[0-7]{1,3}",
            CLexemes::CharConst => "\'.\'",
            CLexemes::StringConst => "\"[^\"]*\"",
            CLexemes::LBracket => "\\[",
            CLexemes::RBracket => "\\]",
            CLexemes::LParen => "\\(",
            CLexemes::RParen => "\\)",
            CLexemes::LBrace => "\\{",
            CLexemes::RBrace => "\\}",
            CLexemes::Dot => "\\.",
            CLexemes::Arrow => "->",
            CLexemes::Increment => "\\+\\+",
            CLexemes::Decrement => "--",
            CLexemes::BitAnd => "&",
            CLexemes::Star => "\\*",
            CLexemes::Plus => "\\+",
            CLexemes::Minus => "-",
            CLexemes::Tilde => "~",
            CLexemes::Bang => "!",
            CLexemes::Slash => "/",
            CLexemes::Percent => "%",
            CLexemes::LShift => "<<",
            CLexemes::RShift => ">>",
            CLexemes::Lt => "<",
            CLexemes::Gt => ">",
            CLexemes::Leq => "<=",
            CLexemes::Geq => ">=",
            CLexemes::Eq => "==",
            CLexemes::Neq => "!=",
            CLexemes::Xor => "^",
            CLexemes::BitOr => "\\|",
            CLexemes::And => "&&",
            CLexemes::Or => "\\|\\|",
            CLexemes::Question => "?",
            CLexemes::Colon => ":",
            CLexemes::Semicolon => ";",
            CLexemes::Ellipsis => "\\.\\.\\.",
            CLexemes::Assign => "=",
            CLexemes::MultAssign => "*=",
            CLexemes::DivAssign => "/=",
            CLexemes::ModAssign => "%=",
            CLexemes::AddAssign => "\\+=",
            CLexemes::SubAssign => "-=",
            CLexemes::LShiftAssign => "<<=",
            CLexemes::RShiftAssign => ">>=",
            CLexemes::AndAssign => "&=",
            CLexemes::XorAssign => "^=",
            CLexemes::OrAssign => "\\|=",
            CLexemes::Comma => ",",
            CLexemes::Comment => "//[^\\n]*\\n",
            CLexemes::MultilineComment => "/\\*([^\\*]|\\*[^/])*\\*/",
            CLexemes::Whitespace => "[ \\t\\n\\v\\f]",
            CLexemes::Hash => "#",
            CLexemes::HeaderName => "<[^\\n>]+>|\"[^\\n\"]\"",
        }
    }

    fn next(self) -> Option<Self> {
        if self.to_id() >= 94 - 1 { None } else { Some(Self::from_id(self.to_id() + 1)) }
    }
}